[workspace]
resolver = "2"
members = ["engine", "wasm", "datagen", "tablegen"]

[profile.release]
opt-level = 3
debug = false

[profile.dev]
opt-level = 3
debug = true

[profile.test]
opt-level = 3
debug = true
