[workspace]
resolver = "2"
members = [
    "chess-core",
    "table-gen",
    "movgen",
    "engine"
]

[profile.release]
opt-level = 3
debug = false

[profile.dev]
opt-level = 3
debug = true

[profile.test]
opt-level = 3

